import { HotspotLocation, AuthorityAlert, ForecastPoint, CityNode, FutureIntegration } from '../types';

export const SIMULATED_DATA_DISCLAIMER = "SIMULATED DATA — For demonstration and AI hackathon prototyping only. Not an official regulatory CPCB measurement.";

export const INITIAL_HOTSPOTS: HotspotLocation[] = [
  // Ahmedabad
  {
    id: 'HOT-AHM-01',
    city: 'Ahmedabad',
    locationName: 'Vatva & Narol Industrial Corridor',
    coordinates: { lat: 22.9568, lng: 72.6341, svgX: 285, svgY: 480 },
    riskLevel: 'HIGH',
    riskScore: 89,
    signals: {
      pm25: 186,
      pm10: 294,
      temperature: 31,
      humidity: 72,
      windSpeed: 4,
    },
    probableContributingFactors: [
      'Chemical & textile manufacturing boiler emissions',
      'Heavy freight diesel transport idling along Ring Road',
      'Low surface boundary layer height trapping stack plumes',
    ],
    confidence: 94,
    timestamp: '14 mins ago',
    citizenReportCount: 12,
    recommendedAction: 'Deploy mechanized water mist cannons, trigger continuous stack emission audits, and inspect boiler fuels in Phase-II Industrial Estate.',
    wardNumber: 'Ward 42 (Vatva South)',
    dominantSource: 'Industrial',
  },
  {
    id: 'HOT-AHM-02',
    city: 'Ahmedabad',
    locationName: 'Pirana Waste Processing & Highway Junction',
    coordinates: { lat: 22.9812, lng: 72.5714, svgX: 282, svgY: 475 },
    riskLevel: 'HIGH',
    riskScore: 83,
    signals: {
      pm25: 164,
      pm10: 275,
      temperature: 32,
      humidity: 68,
      windSpeed: 5,
    },
    probableContributingFactors: [
      'Smoldering municipal solid waste emissions',
      'Heavy unpaved road dust resuspension by heavy trucks',
      'Localized methane-assisted particulate release',
    ],
    confidence: 91,
    timestamp: '32 mins ago',
    citizenReportCount: 18,
    recommendedAction: 'Immediate landfill perimeter thermal drone scan, deploy mobile bio-capping foam units, and establish water sprinkling barrier.',
    wardNumber: 'Ward 38 (Danilimda-Pirana)',
    dominantSource: 'Biomass/Waste',
  },
  {
    id: 'HOT-AHM-03',
    city: 'Ahmedabad',
    locationName: 'SG Highway & ISKCON Flyover Junction',
    coordinates: { lat: 23.0286, lng: 72.5074, svgX: 278, svgY: 470 },
    riskLevel: 'MEDIUM',
    riskScore: 58,
    signals: {
      pm25: 84,
      pm10: 162,
      temperature: 30,
      humidity: 58,
      windSpeed: 9,
    },
    probableContributingFactors: [
      'Peak commercial corridor vehicular queue idling',
      'Flyover construction and unpaved shoulder dust',
    ],
    confidence: 86,
    timestamp: '1 hr ago',
    citizenReportCount: 7,
    recommendedAction: 'Optimize synchronized smart traffic signaling to reduce idle times; wet-sweep flyover underpass segments.',
    wardNumber: 'Ward 14 (Bodakdev)',
    dominantSource: 'Vehicular',
  },
  {
    id: 'HOT-AHM-04',
    city: 'Ahmedabad',
    locationName: 'Sabarmati Riverfront Biodiversity Park',
    coordinates: { lat: 23.0378, lng: 72.5802, svgX: 284, svgY: 468 },
    riskLevel: 'LOW',
    riskScore: 28,
    signals: {
      pm25: 32,
      pm10: 68,
      temperature: 28,
      humidity: 62,
      windSpeed: 14,
    },
    probableContributingFactors: [
      'Riparian green canopy vegetative particulate filtration',
      'Effective urban wind corridor ventilation from river channel',
    ],
    confidence: 89,
    timestamp: '45 mins ago',
    citizenReportCount: 2,
    recommendedAction: 'Maintain baseline vegetative monitoring and maintain EV-only riparian access zones.',
    wardNumber: 'Ward 08 (Usmanpura)',
    dominantSource: 'Mixed',
  },

  // Delhi
  {
    id: 'HOT-DEL-01',
    city: 'Delhi',
    locationName: 'Anand Vihar Inter-State Transit Hub',
    coordinates: { lat: 28.6469, lng: 77.3164, svgX: 410, svgY: 285 },
    riskLevel: 'HIGH',
    riskScore: 96,
    signals: {
      pm25: 298,
      pm10: 482,
      temperature: 24,
      humidity: 84,
      windSpeed: 2.5,
    },
    probableContributingFactors: [
      'Severe thermal inversion layer trapping particulate under 250m ceiling',
      'Non-destined inter-state heavy commercial diesel vehicle congestion',
      'High background road dust and unpaved bus depot surface resuspension',
    ],
    confidence: 97,
    timestamp: '8 mins ago',
    citizenReportCount: 34,
    recommendedAction: 'Enforce Stage IV emergency response: automated water mist canon deployment, ban non-BS-VI diesel transit, and continuous traffic diversion.',
    wardNumber: 'Ward 204 (Anand Vihar)',
    dominantSource: 'Vehicular',
  },
  {
    id: 'HOT-DEL-02',
    city: 'Delhi',
    locationName: 'Jahangirpuri & Okhla Industrial Cluster',
    coordinates: { lat: 28.7264, lng: 77.1685, svgX: 405, svgY: 278 },
    riskLevel: 'HIGH',
    riskScore: 91,
    signals: {
      pm25: 242,
      pm10: 390,
      temperature: 25,
      humidity: 79,
      windSpeed: 3,
    },
    probableContributingFactors: [
      'Metal fabrication & rubber recovery unit emissions',
      'Stagnant wind corridor with transboundary agricultural plume mixing',
    ],
    confidence: 93,
    timestamp: '22 mins ago',
    citizenReportCount: 21,
    recommendedAction: 'Deploy DPCC flying inspection squads to seal illegal fuel burners; mandate zero-emission hours for industrial cluster generators.',
    wardNumber: 'Ward 18 (Jahangirpuri)',
    dominantSource: 'Industrial',
  },
  {
    id: 'HOT-DEL-03',
    city: 'Delhi',
    locationName: 'Nehru Park & Diplomatic Enclave (Chanakyapuri)',
    coordinates: { lat: 28.5912, lng: 77.1906, svgX: 407, svgY: 292 },
    riskLevel: 'LOW',
    riskScore: 36,
    signals: {
      pm25: 42,
      pm10: 82,
      temperature: 26,
      humidity: 65,
      windSpeed: 8,
    },
    probableContributingFactors: [
      'Extensive urban tree canopy microclimate buffering',
      'Strict low-emission transit regulation in central zone',
    ],
    confidence: 88,
    timestamp: '50 mins ago',
    citizenReportCount: 3,
    recommendedAction: 'Continue ambient air baseline calibration and automated smart sensor telemetry.',
    wardNumber: 'Ward 142 (Chanakyapuri)',
    dominantSource: 'Mixed',
  },

  // Mumbai
  {
    id: 'HOT-MUM-01',
    city: 'Mumbai',
    locationName: 'Chembur-Mahul Refinery & Fertilizer Belt',
    coordinates: { lat: 19.0178, lng: 72.8988, svgX: 290, svgY: 620 },
    riskLevel: 'HIGH',
    riskScore: 84,
    signals: {
      pm25: 158,
      pm10: 245,
      temperature: 30,
      humidity: 86,
      windSpeed: 6,
    },
    probableContributingFactors: [
      'Petrochemical refinery flare and volatile organic compound aerosolization',
      'Marine humidity trapping sulfate and nitrate particulate aerosols',
      'Port-bound container freight trailer diesel emissions',
    ],
    confidence: 92,
    timestamp: '18 mins ago',
    citizenReportCount: 16,
    recommendedAction: 'Execute MPCB emission compliance check on vapor recovery units; activate coastal anti-smog misting curtains.',
    wardNumber: 'Ward M-West (Chembur)',
    dominantSource: 'Industrial',
  },
  {
    id: 'HOT-MUM-02',
    city: 'Mumbai',
    locationName: 'BKC Coastal Road Construction Zone',
    coordinates: { lat: 19.0657, lng: 72.8687, svgX: 288, svgY: 614 },
    riskLevel: 'MEDIUM',
    riskScore: 64,
    signals: {
      pm25: 98,
      pm10: 210,
      temperature: 29,
      humidity: 82,
      windSpeed: 7,
    },
    probableContributingFactors: [
      'Uncovered aggregate transit and excavation drilling dust',
      'Peak financial district taxi and bus idling during evening rush',
    ],
    confidence: 87,
    timestamp: '40 mins ago',
    citizenReportCount: 11,
    recommendedAction: 'Enforce mandatory geotextile covers over debris stock; increase water sprinkling frequency on haul roads to 4x daily.',
    wardNumber: 'Ward H-East (Bandra Kurla)',
    dominantSource: 'Construction Dust',
  },
  {
    id: 'HOT-MUM-03',
    city: 'Mumbai',
    locationName: 'Marine Drive Coastal Promenade',
    coordinates: { lat: 18.9438, lng: 72.8233, svgX: 285, svgY: 628 },
    riskLevel: 'LOW',
    riskScore: 31,
    signals: {
      pm25: 35,
      pm10: 74,
      temperature: 29,
      humidity: 88,
      windSpeed: 18,
    },
    probableContributingFactors: [
      'Strong Arabian Sea onshore wind breeze driving rapid pollutant dispersion',
      'Limited stationary industrial sources in immediate coastal strip',
    ],
    confidence: 90,
    timestamp: '1 hr ago',
    citizenReportCount: 4,
    recommendedAction: 'Maintain baseline coastal monitoring; use high-ventilation data for boundary model calibration.',
    wardNumber: 'Ward A (Churchgate-Colaba)',
    dominantSource: 'Mixed',
  },

  // Bengaluru
  {
    id: 'HOT-BLR-01',
    city: 'Bengaluru',
    locationName: 'Silk Board - Outer Ring Road Interchange',
    coordinates: { lat: 12.9177, lng: 77.6238, svgX: 415, svgY: 820 },
    riskLevel: 'HIGH',
    riskScore: 78,
    signals: {
      pm25: 142,
      pm10: 236,
      temperature: 26,
      humidity: 64,
      windSpeed: 4.5,
    },
    probableContributingFactors: [
      'Severe stop-and-go tech corridor vehicular congestion (avg speed 6 km/h)',
      'Metro Line construction unpaved lane dust resuspension',
      'Localized diesel generator use in nearby commercial tech towers',
    ],
    confidence: 90,
    timestamp: '25 mins ago',
    citizenReportCount: 22,
    recommendedAction: 'Deploy BBMP traffic de-bottlenecking teams; mandate wet sweeping of metro construction lanes twice per shift.',
    wardNumber: 'Ward 174 (HSR Layout)',
    dominantSource: 'Vehicular',
  },
  {
    id: 'HOT-BLR-02',
    city: 'Bengaluru',
    locationName: 'Whitefield - ITPL Industrial & Tech Park',
    coordinates: { lat: 12.9863, lng: 77.7335, svgX: 422, svgY: 812 },
    riskLevel: 'MEDIUM',
    riskScore: 61,
    signals: {
      pm25: 88,
      pm10: 178,
      temperature: 27,
      humidity: 59,
      windSpeed: 6.8,
    },
    probableContributingFactors: [
      'Commercial expansion construction work',
      'Heavy fleet bus movements and goods carriage transit',
    ],
    confidence: 85,
    timestamp: '35 mins ago',
    citizenReportCount: 9,
    recommendedAction: 'Audit construction site dust suppression compliance; adjust feeder bus scheduling to eliminate idling queues.',
    wardNumber: 'Ward 84 (Whitefield)',
    dominantSource: 'Construction Dust',
  },
  {
    id: 'HOT-BLR-03',
    city: 'Bengaluru',
    locationName: 'Cubbon Park Botanical Enclave',
    coordinates: { lat: 12.9763, lng: 77.5929, svgX: 412, svgY: 815 },
    riskLevel: 'LOW',
    riskScore: 24,
    signals: {
      pm25: 26,
      pm10: 52,
      temperature: 25,
      humidity: 60,
      windSpeed: 9,
    },
    probableContributingFactors: [
      'Dense urban forest micro-filtration (300+ acre lung space)',
      'Vehicular traffic restricted within inner ring loop',
    ],
    confidence: 92,
    timestamp: '15 mins ago',
    citizenReportCount: 1,
    recommendedAction: 'Preserve urban lung baseline and correlate tree density with micro-climate cooling.',
    wardNumber: 'Ward 111 (Shantala Nagar)',
    dominantSource: 'Mixed',
  },
];

export const INITIAL_AUTHORITY_ALERTS: AuthorityAlert[] = [
  {
    id: 'ALT-2026-881',
    location: 'Anand Vihar Inter-State Hub',
    city: 'Delhi',
    riskLevel: 'HIGH',
    riskScore: 96,
    evidence: [
      '34 citizen reports received within past 60 minutes describing heavy choking smog',
      'Sensor telemetry: PM2.5 at 298 µg/m³ (5.9x standard), PM10 at 482 µg/m³',
      'Atmospheric stagnation: 2.5 km/h wind with boundary inversion height < 250m',
    ],
    aiAssessment: 'Critical localized smog event triggered by diesel fleet accumulation combined with evening thermal inversion trap.',
    recommendedAction: 'Immediate deployment of 4 mobile water mist canons, divert inter-state diesel trucks to Western Peripheral Expressway, and issue public health advisory for sensitive groups.',
    confidence: 97,
    timestamp: '10 mins ago',
    status: 'PENDING_REVIEW',
    priority: 'CRITICAL',
  },
  {
    id: 'ALT-2026-879',
    location: 'Vatva & Narol Industrial Corridor',
    city: 'Ahmedabad',
    riskLevel: 'HIGH',
    riskScore: 89,
    evidence: [
      '12 citizen observations reporting dense chemical odor and dark plume',
      'Sensor readings: PM2.5 at 186 µg/m³, PM10 at 294 µg/m³, wind 4 km/h',
      'Anomalous ratio PM2.5/PM10 = 0.63 indicating high combustion aerosol fraction',
    ],
    aiAssessment: 'Severe industrial emission surge from chemical boiler cluster compounded by low nocturnal wind dispersion.',
    recommendedAction: 'GPCB task force dispatch for nocturnal fuel combustion audit; activate industrial estate mist suppression network.',
    confidence: 94,
    timestamp: '25 mins ago',
    status: 'DISPATCHED',
    priority: 'CRITICAL',
    dispatchedTo: 'GPCB Regional Office & Ahmedabad Municipal Task Force Unit 3',
    dispatchTimestamp: '15 mins ago',
  },
  {
    id: 'ALT-2026-874',
    location: 'Chembur-Mahul Refinery Belt',
    city: 'Mumbai',
    riskLevel: 'HIGH',
    riskScore: 84,
    evidence: [
      '16 citizen observations with geo-tagged images of sulfurous haze',
      'PM2.5 elevated at 158 µg/m³ with relative humidity 86%',
      'Secondary aerosol condensation detected under marine boundary layer',
    ],
    aiAssessment: 'Petrochemical flare VOC emissions interacting with high coastal humidity to form secondary particulate haze.',
    recommendedAction: 'Issue alert to refinery operators to minimize flare flushes; activate BMC mobile mist sprinklers along Mahul corridor.',
    confidence: 92,
    timestamp: '42 mins ago',
    status: 'MITIGATING',
    priority: 'CRITICAL',
    dispatchedTo: 'MPCB Industrial Response Team & BMC Disaster Management Cell',
    dispatchTimestamp: '30 mins ago',
  },
  {
    id: 'ALT-2026-868',
    location: 'Silk Board - ORR Interchange',
    city: 'Bengaluru',
    riskLevel: 'HIGH',
    riskScore: 78,
    evidence: [
      '22 citizen reports citing dense vehicle exhaust and gridlock smoke',
      'PM2.5 at 142 µg/m³, localized average vehicle transit speed under 5 km/h',
    ],
    aiAssessment: 'Peak hour vehicular idling spike with unpaved road dust resuspension around metro construction pylons.',
    recommendedAction: 'BBMP traffic police traffic green wave intervention; mandatory wet sweeping of excavation stretch.',
    confidence: 90,
    timestamp: '1 hr ago',
    status: 'RESOLVED',
    priority: 'ELEVATED',
    dispatchedTo: 'Bengaluru Traffic Police & BBMP Solid Waste Management Cell',
    dispatchTimestamp: '50 mins ago',
  },
  {
    id: 'ALT-2026-862',
    location: 'BKC Coastal Road Construction Zone',
    city: 'Mumbai',
    riskLevel: 'MEDIUM',
    riskScore: 64,
    evidence: [
      '11 reports of dust clouds near excavation trench',
      'PM10 reading 210 µg/m³ (significantly outpacing PM2.5)',
    ],
    aiAssessment: 'Mechanical dust resuspension from unmitigated earthworks during transit hours.',
    recommendedAction: 'Mandate immediate tarpaulin covers on stockpiles and deploy continuous water bowsers.',
    confidence: 87,
    timestamp: '2 hrs ago',
    status: 'RESOLVED',
    priority: 'ROUTINE',
  },
];

export const HOURLY_FORECAST_DATA: ForecastPoint[] = [
  { timeLabel: 'Now (03:00)', hourOffset: 0, riskScore: 84, riskLevel: 'HIGH', pm25: 172, pm10: 280, windSpeed: 3.5, inversionRisk: 'Severe', dispersionIndex: 22 },
  { timeLabel: '+1h (04:00)', hourOffset: 1, riskScore: 88, riskLevel: 'HIGH', pm25: 184, pm10: 298, windSpeed: 3.0, inversionRisk: 'Severe', dispersionIndex: 18 },
  { timeLabel: '+2h (05:00)', hourOffset: 2, riskScore: 92, riskLevel: 'HIGH', pm25: 196, pm10: 315, windSpeed: 2.8, inversionRisk: 'Severe', dispersionIndex: 15 },
  { timeLabel: '+3h (06:00)', hourOffset: 3, riskScore: 95, riskLevel: 'HIGH', pm25: 210, pm10: 340, windSpeed: 3.2, inversionRisk: 'Severe', dispersionIndex: 14 },
  { timeLabel: '+4h (07:00)', hourOffset: 4, riskScore: 91, riskLevel: 'HIGH', pm25: 198, pm10: 325, windSpeed: 4.5, inversionRisk: 'Moderate', dispersionIndex: 28 },
  { timeLabel: '+6h (09:00)', hourOffset: 6, riskScore: 78, riskLevel: 'HIGH', pm25: 160, pm10: 260, windSpeed: 7.2, inversionRisk: 'Moderate', dispersionIndex: 42 },
  { timeLabel: '+8h (11:00)', hourOffset: 8, riskScore: 62, riskLevel: 'MEDIUM', pm25: 118, pm10: 195, windSpeed: 11.5, inversionRisk: 'Low', dispersionIndex: 68 },
  { timeLabel: '+12h (15:00)', hourOffset: 12, riskScore: 48, riskLevel: 'MEDIUM', pm25: 85, pm10: 152, windSpeed: 14.0, inversionRisk: 'Low', dispersionIndex: 82 },
  { timeLabel: '+16h (19:00)', hourOffset: 16, riskScore: 72, riskLevel: 'HIGH', pm25: 145, pm10: 240, windSpeed: 6.0, inversionRisk: 'Moderate', dispersionIndex: 45 },
  { timeLabel: '+20h (23:00)', hourOffset: 20, riskScore: 82, riskLevel: 'HIGH', pm25: 168, pm10: 275, windSpeed: 4.0, inversionRisk: 'Severe', dispersionIndex: 26 },
  { timeLabel: '+24h (03:00+1)', hourOffset: 24, riskScore: 80, riskLevel: 'HIGH', pm25: 162, pm10: 265, windSpeed: 4.2, inversionRisk: 'Severe', dispersionIndex: 29 },
];

export const CITY_INTELLIGENCE_NODES: CityNode[] = [
  {
    city: 'Ahmedabad',
    state: 'Gujarat',
    activeHotspots: 4,
    avgRiskScore: 64,
    topPollutant: 'PM10 & Industrial VOCs',
    dominantChallenge: 'Industrial boiler clusters & unpaved highway dust corridors',
    edgeModelVersion: 'v2.4-ahm-industrial',
    localDatasetSize: 4280,
    lastFederatedSync: '6 mins ago',
    coordinates: { lat: 23.0225, lng: 72.5714 },
    sharedInsights: [
      'Trained non-linear humidity/chemical aerosol interaction weights for semi-arid zones',
      'Shared night-shift boiler emission thermal plume dispersion signatures',
      'Calibrated dry-season road dust resuspension coefficient',
    ],
  },
  {
    city: 'Delhi',
    state: 'NCT Delhi',
    activeHotspots: 7,
    avgRiskScore: 84,
    topPollutant: 'PM2.5 & Fine Combustion Aerosols',
    dominantChallenge: 'Winter boundary layer inversion & transit fleet density',
    edgeModelVersion: 'v3.1-del-inversion',
    localDatasetSize: 12450,
    lastFederatedSync: '3 mins ago',
    coordinates: { lat: 28.6139, lng: 77.209 },
    sharedInsights: [
      'Exported sub-200m boundary layer inversion trapping probability weights',
      'Contributed heavy diesel freight corridor stop-and-go emission models',
      'Synchronized transboundary stubble smoke optical signature classifier',
    ],
  },
  {
    city: 'Mumbai',
    state: 'Maharashtra',
    activeHotspots: 3,
    avgRiskScore: 59,
    topPollutant: 'Secondary Sulfate PM2.5 & Coastal NO2',
    dominantChallenge: 'High marine humidity trapping refinery & coastal construction aerosols',
    edgeModelVersion: 'v2.1-mum-marine',
    localDatasetSize: 6890,
    lastFederatedSync: '9 mins ago',
    coordinates: { lat: 19.076, lng: 72.8777 },
    sharedInsights: [
      'Contributed coastal sea-breeze diurnal ventilation dispersion model',
      'Shared high-humidity hygroscopic particulate growth curves',
      'Calibrated port logistics marine diesel flare parameters',
    ],
  },
  {
    city: 'Bengaluru',
    state: 'Karnataka',
    activeHotspots: 4,
    avgRiskScore: 54,
    topPollutant: 'Vehicular Resuspended PM10 & Black Carbon',
    dominantChallenge: 'Tech corridor choke-point idling & rapid infrastructure construction',
    edgeModelVersion: 'v2.0-blr-traffic',
    localDatasetSize: 5340,
    lastFederatedSync: '12 mins ago',
    coordinates: { lat: 12.9716, lng: 77.5946 },
    sharedInsights: [
      'Shared micro-elevation valley trap models for plateau city terrain',
      'Contributed smart traffic signal de-bottlenecking emission reduction metrics',
      'Calibrated urban tree canopy filtration absorption coefficients',
    ],
  },
];

export const FUTURE_INTEGRATIONS_DATA: FutureIntegration[] = [
  {
    id: 'INT-01',
    title: 'Satellite Remote Sensing Feeds',
    category: 'Orbital Earth Observation',
    iconName: 'Satellite',
    description: 'Direct ingestion of Copernicus Sentinel-5P TROPOMI satellite rasters for column NO2, SO2, Carbon Monoxide, and Aerosol Optical Depth (AOD) across the Indian subcontinent.',
    dataSources: ['ESA Copernicus Sentinel-5P', 'NASA MODIS / VIIRS AOD', 'ISRO INSAT-3D Aerosol Products'],
    valueAdd: 'Fills ground sensor blind spots in suburban belts and quantifies regional transboundary smoke plumes.',
    technicalFeasibility: 'REST API via Google Earth Engine & Sentinel Hub Open Access Hub.',
    status: 'Coming in the next version',
  },
  {
    id: 'INT-02',
    title: 'High-Resolution Weather & Dispersion APIs',
    category: 'Meteorological Intelligence',
    iconName: 'CloudSun',
    description: 'Live real-time surface meteorological observations (temperature, humidity, wind velocity, and direction) are actively retrieved via Open-Meteo API. Future releases will expand into 3D numerical boundary layer inversion modeling (IMD WRF & ECMWF).',
    dataSources: ['Open-Meteo Weather API (LIVE)', 'India Meteorological Department (IMD) WRF', 'ECMWF Copernicus CAMS'],
    valueAdd: 'Supplies real-time atmospheric boundary conditions for physical aerosol dispersion modeling.',
    technicalFeasibility: 'Active Open-Meteo live REST client with sub-minute caching & fallback resilience.',
    status: 'LIVE (Open-Meteo Connected)',
  },
  {
    id: 'INT-03',
    title: 'Low-Cost IoT Air Quality Sensor Networks',
    category: 'Hyperlocal Physical Hardware',
    iconName: 'Cpu',
    description: 'MQTT/CoAP ingestion from deployed low-cost laser optical particle counter (OPC) sensors (e.g. Plantower, Sensirion) mounted on city municipal buses, street poles, and school rooftops.',
    dataSources: ['OpenSenseMap', 'LoRaWAN Municipal Mesh Nodes', 'Custom ESP32 PM2.5/PM10 Telemetry'],
    valueAdd: 'Increases spatial resolution down to 100-meter street-level resolution for real-time hotspot detection.',
    technicalFeasibility: 'TimescaleDB / PubSub ingest broker with auto-calibration AI algorithms.',
    status: 'Coming in the next version',
  },
  {
    id: 'INT-04',
    title: 'Citizen Photo Computer Vision Haze Index',
    category: 'Multimodal AI Vision',
    iconName: 'Camera',
    description: 'Automated optical transmission and haze depth estimation using vision foundation models on citizen camera photos to estimate visual range and contrast degradation without physical sensors.',
    dataSources: ['Crowdsourced Mobile Camera Uploads', 'Traffic Surveillance Camera RTSP Feeds', 'Dashcam Streams'],
    valueAdd: 'Instantly turns any smartphone photo into a verifiable particulate density signal.',
    technicalFeasibility: 'Gemini 3.7 Vision & Dark Channel Prior (DCP) transmission mapping.',
    status: 'Coming in the next version',
  },
  {
    id: 'INT-05',
    title: 'CPCB / CAAQMS Live Regulatory Network Stream',
    category: 'Official Regulatory Benchmarking',
    iconName: 'ShieldCheck',
    description: 'Real-time telemetry integration with continuous ambient air quality monitoring stations (CAAQMS) operated by the Central Pollution Control Board and State Pollution Control Boards.',
    dataSources: ['CPCB National Air Quality Index Portal', 'State PCB CAAQMS APIs', 'OpenAQ Global Air API'],
    valueAdd: 'Provides reference ground-truth calibration for low-cost sensors and citizen reports.',
    technicalFeasibility: 'Automated sync adapter with automated sensor drift correction.',
    status: 'Coming in the next version',
  },
];

export const PRESET_CITIZEN_REPORTS = [
  {
    name: 'Ahmedabad Industrial Corridor (High Alert)',
    city: 'Ahmedabad',
    location: 'Vatva GIDC Phase II near Ring Road Canal',
    description: 'Pungent chemical and sulfuric odor observed since early morning. Visible grey-black smoke plume venting from boiler chimneys with low ceiling haze.',
    pm25: 186,
    pm10: 294,
    temperature: 31,
    humidity: 72,
    windSpeed: 4,
  },
  {
    name: 'Delhi Anand Vihar Winter Smog (Critical)',
    city: 'Delhi',
    location: 'Anand Vihar ISBT & Railway Crossing Underpass',
    description: 'Thick stinging smog layer severely reducing visibility to under 150m. Continuous line of idling diesel buses and open waste burning along railway tracks.',
    pm25: 298,
    pm10: 482,
    temperature: 24,
    humidity: 84,
    windSpeed: 2,
  },
  {
    name: 'Mumbai Chembur Refinery Belt (Elevated)',
    city: 'Mumbai',
    location: 'Mahul Road near Eastern Freeway Corridor',
    description: 'Strong petrochemical smell with heavy humid haze hanging over residential tenements. Flare stacks active with visible flare discharge.',
    pm25: 158,
    pm10: 245,
    temperature: 30,
    humidity: 86,
    windSpeed: 6,
  },
  {
    name: 'Bengaluru Silk Board Traffic Gridlock (Moderate-High)',
    city: 'Bengaluru',
    location: 'Central Silk Board Junction - Madiwala flyover entry',
    description: 'Dense dark exhaust smoke from stationary city buses and freight trucks idling in gridlock. Flyover metro piling work throwing up dry unpaved dust.',
    pm25: 142,
    pm10: 236,
    temperature: 26,
    humidity: 64,
    windSpeed: 4,
  },
  {
    name: 'Ahmedabad Sabarmati Riverfront (Clean Baseline)',
    city: 'Ahmedabad',
    location: 'Sabarmati Riverfront Promenade West, Usmanpura',
    description: 'Clear morning skies with light river breeze. Low traffic and pleasant air quality along the tree-lined pedestrian pathway.',
    pm25: 32,
    pm10: 68,
    temperature: 28,
    humidity: 62,
    windSpeed: 14,
  },
];
